import { chromium } from '@playwright/test';
const b = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium-1194/chrome-linux/chrome' });
const p = await b.newPage({ viewport: { width: 1440, height: 900 } });
const errs = [];
p.on('console', m => { if (m.type() === 'error' || m.type() === 'warning') errs.push(m.text().slice(0,300)); });
p.on('pageerror', e => errs.push('PAGEERROR ' + String(e).slice(0,300)));
await p.goto('http://localhost:6006/iframe.html?id=viewer-genericviewer--mermaid-inline-pan-zoom&viewMode=story', { waitUntil: 'networkidle' });
await p.waitForTimeout(4000);
console.log('BODY:', (await p.evaluate(() => document.body.innerText)).slice(0, 400));
console.log('HTML:', (await p.evaluate(() => document.querySelector('.mermaid-root')?.outerHTML ?? document.body.innerHTML)).slice(0, 600));
console.log('ERRORS:', JSON.stringify(errs.slice(0,6), null, 1));
await b.close();
