packages:
  - "."
  - "forge-console"
  - "workers/cron-aggregate"
  - "workers/agent-link"
allowBuilds:
  '@forge/cli': set this to true or false
  '@scarf/scarf': set this to true or false
  '@tree-sitter-grammars/tree-sitter-yaml': set this to true or false
  cloudflared: set this to true or false
  core-js: set this to true or false
  core-js-pure: set this to true or false
  esbuild: set this to true or false
  iframe-resizer: set this to true or false
  keytar: set this to true or false
  protobufjs: set this to true or false
  react-ace: set this to true or false
  sharp: set this to true or false
  swagger-editor: set this to true or false
  tree-sitter: set this to true or false
  tree-sitter-json: set this to true or false
  workerd: set this to true or false
