compatibility_flags = [ "nodejs_compat" ]
compatibility_date = "2024-11-11"

name="confluence-plugin"
pages_build_output_dir = "dist"

[vars]
DIAGRAMLY_BACKEND_API_BASE_URL = "https://staging.diagramly.ai"
ENVIRONMENT = "development"  # Set to "development" for local development
ALLOWED_FORGE_APP_IDS = "8ad26115-211f-4216-971b-0540f606303d" # Lite app id

[env.production.vars]
DIAGRAMLY_BACKEND_API_BASE_URL = "https://staging.diagramly.ai"
ENVIRONMENT = "production"
ALLOWED_FORGE_APP_IDS = "8ad26115-211f-4216-971b-0540f606303d,01ede8b1-4e88-451a-b9ef-89eeef93afaf" # ZenUML Lite and Diagramly

[[ env.preview.d1_databases ]]
binding = "DB"
database_name = "confluence-plugin"
database_id = "78530089-656d-482f-b38b-60f4f6765cc6"
migrations_dir = "functions/migrations"

[[ env.production.d1_databases ]]
binding = "DB"
database_name = "confluence-plugin"
database_id = "78530089-656d-482f-b38b-60f4f6765cc6"
migrations_dir = "functions/migrations"

[[ d1_databases ]]
binding = "DB"
database_name = "confluence-plugin"
database_id = "78530089-656d-482f-b38b-60f4f6765cc6"
migrations_dir = "functions/migrations"

[[ env.production.r2_buckets ]]
binding = "EVENT_BUCKET"
bucket_name = "atlassian-events"