import { mount } from '@vue/test-utils'
import { vi, describe, it, expect, beforeEach } from 'vitest'
import Viewer from './MermaidHighlightViewer.vue'
import forgeGlobal from '@/model/globals/forgeGlobal'
import store from '@/model/store2'
import { trackAnalyticsEvent } from '@/utils/analytics/trackAnalyticsEvent'
vi.mock('@/utils/analytics/trackAnalyticsEvent', () => ({ trackAnalyticsEvent: vi.fn() }))
vi.mock('@/components/Mermaid.vue', () => ({ default: { name: 'Mermaid', methods: { setCaptureMode: vi.fn() }, props: ['relationshipHighlights'], template: '<div />' } }))
// Option 1e: the switch lives in the More menu (viewer-more-menu-start slot,
// which hands the item a close() for the menu) and the overlays in the canvas.
vi.mock('./GenericViewer.vue', () => ({ default: {
  name: 'GenericViewer', props: ['wide', 'hideHeader'], data: () => ({ closed: 0 }),
  template: '<div><slot name="viewer-more-menu-start" :close="() => closed++"/><slot/><slot name="viewer-canvas-overlay"/></div>',
} }))
const SWITCH = '[role="menuitemcheckbox"]'
const PILL_CLOSE = '[aria-label="Dismiss relationship highlight feedback"]'
const HINT_CLOSE = '[aria-label="Dismiss highlight hint"]'
const HINT_KEY = 'zenuml.mermaidHighlightHint.v1'
const mountViewer = () => mount(Viewer)
const calls = (name: string) => vi.mocked(trackAnalyticsEvent).mock.calls.filter(c => c[0] === name)
const use = (renderer: any, kinds: string[]) => kinds.forEach(kind => renderer.vm.$emit('highlight-used', { kind }))
const turnOff = async (wrapper: any) => { const b = wrapper.findAll('.highlight-hint button').find((x: any) => x.text() === 'Turn off'); expect(b).toBeTruthy(); await b.trigger('click') }
describe('real highlight viewer lifecycle', () => {
  beforeEach(() => { vi.clearAllMocks(); localStorage.clear(); forgeGlobal.forgeContext = {}; store.state.diagram.id = 'first'; store.state.diagram.mermaidCode = 'flowchart LR\nA-->B' })
  it('offers no menu switch, hint, or feedback for unsupported renderers', async () => {
    const wrapper = mountViewer()
    wrapper.findComponent({ name: 'Mermaid' }).vm.$emit('highlight-ready', false)
    await wrapper.vm.$nextTick()
    expect(wrapper.find(SWITCH).exists()).toBe(false)
    expect(wrapper.find('.highlight-hint').exists()).toBe(false)
    expect(wrapper.find('.highlight-pill').exists()).toBe(false)
  })
  it('forwards capture mode synchronously, hides both overlays during capture, and records fullscreen context', async () => {
    forgeGlobal.forgeContext = { extension: { modal: { macroMode: 'fullscreen' } } }
    const wrapper = mountViewer()
    const renderer = wrapper.findComponent({ name: 'Mermaid' })
    const generic = wrapper.findComponent({ name: 'GenericViewer' })
    const capture = vi.spyOn(renderer.vm, 'setCaptureMode')
    generic.vm.$emit('capture-mode-change', true)
    expect(capture).toHaveBeenCalledWith(true)
    renderer.vm.$emit('highlight-ready', true)
    use(renderer, ['node'])
    await wrapper.vm.$nextTick()
    expect(trackAnalyticsEvent).toHaveBeenCalledWith('mermaid_highlight_used', expect.objectContaining({ surface: 'fullscreen' }))
    expect(wrapper.find('.highlight-hint').exists()).toBe(false)
    expect(calls('mermaid_highlight_hint_shown')).toHaveLength(0)
    generic.vm.$emit('capture-mode-change', false)
    await wrapper.vm.$nextTick()
    expect(wrapper.find('.highlight-hint').exists()).toBe(true)
    expect(trackAnalyticsEvent).toHaveBeenCalledWith('mermaid_highlight_hint_shown', expect.objectContaining({ surface: 'fullscreen', macro_type: 'mermaid' }))
    use(renderer, ['edge', 'node'])
    await wrapper.vm.$nextTick()
    expect(wrapper.find('.highlight-pill').exists()).toBe(true)
    expect(wrapper.find('.highlight-hint').exists()).toBe(false)
    expect(trackAnalyticsEvent).toHaveBeenCalledWith('mermaid_highlight_feedback_shown', expect.objectContaining({ surface: 'fullscreen', highlight_use_count: 3 }))
  })
  it('switches highlights from the More menu, closes the menu, and starts a new diagram enabled', async () => {
    const wrapper = mountViewer()
    const renderer = wrapper.findComponent({ name: 'Mermaid' })
    const generic = wrapper.findComponent({ name: 'GenericViewer' })
    renderer.vm.$emit('highlight-ready', true)
    await wrapper.vm.$nextTick()
    expect(wrapper.get(SWITCH).attributes('aria-checked')).toBe('true')
    expect(wrapper.get(SWITCH).text()).toContain('Relationship highlights')
    await wrapper.get(SWITCH).trigger('click')
    expect(renderer.props('relationshipHighlights')).toBe(false)
    expect(wrapper.get(SWITCH).attributes('aria-checked')).toBe('false')
    expect((generic.vm as any).closed).toBe(1)
    expect(trackAnalyticsEvent).toHaveBeenCalledWith('mermaid_highlight_preference_changed', expect.objectContaining({ highlight_enabled: false, action_location: 'header_more_menu' }))
    expect(wrapper.emitted('enabled-change')?.at(-1)).toEqual([false])
    store.state.diagram.mermaidCode = 'flowchart LR\nC-->D'
    await wrapper.vm.$nextTick()
    expect(renderer.props('relationshipHighlights')).toBe(true)
    expect(wrapper.emitted('enabled-change')?.at(-1)).toEqual([true])
    renderer.vm.$emit('highlight-ready', true)
    await wrapper.vm.$nextTick()
    expect(wrapper.get(SWITCH).attributes('aria-checked')).toBe('true')
  })
  it('shows the hint once per device on the first use; × dismisses it and it never returns', async () => {
    const wrapper = mountViewer()
    const renderer = wrapper.findComponent({ name: 'Mermaid' })
    renderer.vm.$emit('highlight-ready', true)
    await wrapper.vm.$nextTick()
    expect(wrapper.find('.highlight-hint').exists()).toBe(false)
    use(renderer, ['node'])
    await wrapper.vm.$nextTick()
    expect(wrapper.get('.highlight-hint').text()).toContain('Highlighting connections')
    expect(JSON.parse(localStorage.getItem(HINT_KEY) || '{}')).toEqual({ seen: true })
    await wrapper.get(HINT_CLOSE).trigger('click')
    expect(wrapper.find('.highlight-hint').exists()).toBe(false)
    expect(trackAnalyticsEvent).toHaveBeenCalledWith('mermaid_highlight_hint_dismissed', expect.objectContaining({ highlight_dismiss_cause: 'close' }))
    expect(renderer.props('relationshipHighlights')).toBe(true)
    store.state.diagram.id = 'second'
    await wrapper.vm.$nextTick()
    renderer.vm.$emit('highlight-ready', true)
    use(renderer, ['edge'])
    await wrapper.vm.$nextTick()
    expect(wrapper.find('.highlight-hint').exists()).toBe(false)
    expect(calls('mermaid_highlight_hint_shown')).toHaveLength(1)
    const later = mountViewer()
    const laterRenderer = later.findComponent({ name: 'Mermaid' })
    laterRenderer.vm.$emit('highlight-ready', true)
    use(laterRenderer, ['node'])
    await later.vm.$nextTick()
    expect(later.find('.highlight-hint').exists()).toBe(false)
  })
  it('Turn off on the hint disables highlights and records the dismissal and the preference', async () => {
    const wrapper = mountViewer()
    const renderer = wrapper.findComponent({ name: 'Mermaid' })
    renderer.vm.$emit('highlight-ready', true)
    use(renderer, ['node'])
    await wrapper.vm.$nextTick()
    await turnOff(wrapper)
    expect(renderer.props('relationshipHighlights')).toBe(false)
    expect(wrapper.find('.highlight-hint').exists()).toBe(false)
    expect(wrapper.get(SWITCH).attributes('aria-checked')).toBe('false')
    expect(trackAnalyticsEvent).toHaveBeenCalledWith('mermaid_highlight_hint_dismissed', expect.objectContaining({ highlight_dismiss_cause: 'turn_off' }))
    expect(trackAnalyticsEvent).toHaveBeenCalledWith('mermaid_highlight_preference_changed', expect.objectContaining({ highlight_enabled: false, action_location: 'canvas_hint' }))
    expect(wrapper.emitted('enabled-change')?.at(-1)).toEqual([false])
    await wrapper.get(SWITCH).trigger('click')
    expect(renderer.props('relationshipHighlights')).toBe(true)
    expect(wrapper.find('.highlight-hint').exists()).toBe(false)
  })
  it('records usage once per diagram, shows the pill on the third use, and resets the count for a new diagram', async () => {
    const wrapper = mountViewer()
    const renderer = wrapper.findComponent({ name: 'Mermaid' })
    renderer.vm.$emit('highlight-ready', true)
    await wrapper.vm.$nextTick()
    use(renderer, ['node', 'edge'])
    await wrapper.vm.$nextTick()
    expect(wrapper.find('.highlight-pill').exists()).toBe(false)
    expect(wrapper.emitted('usage-change')).toEqual([[true]])
    use(renderer, ['group'])
    await wrapper.vm.$nextTick()
    expect(wrapper.find('.highlight-pill').exists()).toBe(true)
    expect(calls('mermaid_highlight_used')).toHaveLength(1)
    store.state.diagram.id = 'second'
    await wrapper.vm.$nextTick()
    expect(wrapper.emitted('usage-change')?.at(-1)).toEqual([false])
    renderer.vm.$emit('highlight-ready', true)
    use(renderer, ['edge', 'edge'])
    await wrapper.vm.$nextTick()
    expect(wrapper.find('.highlight-pill').exists()).toBe(false)
    use(renderer, ['node'])
    await wrapper.vm.$nextTick()
    expect(wrapper.find('.highlight-pill').exists()).toBe(true)
    expect(calls('mermaid_highlight_used')).toHaveLength(2)
    expect(calls('mermaid_highlight_feedback_shown')).toHaveLength(2)
  })
  it('a dismissed pill stays closed through menu toggles and for later diagrams', async () => {
    const wrapper = mountViewer()
    const renderer = wrapper.findComponent({ name: 'Mermaid' })
    renderer.vm.$emit('highlight-ready', true)
    use(renderer, ['node', 'edge', 'node'])
    await wrapper.vm.$nextTick()
    await wrapper.get(PILL_CLOSE).trigger('click')
    expect(wrapper.find('.highlight-pill').exists()).toBe(false)
    await wrapper.get(SWITCH).trigger('click')
    expect(renderer.props('relationshipHighlights')).toBe(false)
    await wrapper.get(SWITCH).trigger('click')
    expect(wrapper.find('.highlight-pill').exists()).toBe(false)
    store.state.diagram.id = 'second'
    await wrapper.vm.$nextTick()
    renderer.vm.$emit('highlight-ready', true)
    use(renderer, ['edge', 'node', 'group'])
    await wrapper.vm.$nextTick()
    expect(wrapper.find('.highlight-pill').exists()).toBe(false)
    expect(calls('mermaid_highlight_used')).toHaveLength(2)
    expect(calls('mermaid_highlight_feedback_shown')).toHaveLength(1)
  })
})
