import { mount } from '@vue/test-utils'
import { vi, describe, it, expect, beforeEach } from 'vitest'
import Viewer from './MermaidHighlightViewer.vue'
import forgeGlobal from '@/model/globals/forgeGlobal'
import store from '@/model/store2'
import { trackAnalyticsEvent } from '@/utils/analytics/trackAnalyticsEvent'
vi.mock('@/utils/analytics/trackAnalyticsEvent', () => ({ trackAnalyticsEvent: vi.fn() }))
vi.mock('@/components/Mermaid.vue', () => ({ default: { name: 'Mermaid', methods: { setCaptureMode: vi.fn() }, props: ['relationshipHighlights'], template: '<div />' } }))
vi.mock('./GenericViewer.vue', () => ({ default: { name: 'GenericViewer', props: ['wide', 'hideHeader'], template: '<div><slot name="viewer-actions"/><slot/><slot name="viewer-canvas-overlay"/></div>' } }))
const CLOSE = '[aria-label="Dismiss relationship highlight feedback"]'
const mountViewer = () => mount(Viewer)
const calls = (name: string) => vi.mocked(trackAnalyticsEvent).mock.calls.filter(c => c[0] === name)
const use = (renderer: any, kinds: string[]) => kinds.forEach(kind => renderer.vm.$emit('highlight-used', { kind }))
describe('real highlight viewer lifecycle', () => {
  beforeEach(() => { vi.clearAllMocks(); localStorage.clear(); forgeGlobal.forgeContext = {}; store.state.diagram.id = 'first'; store.state.diagram.mermaidCode = 'flowchart LR\nA-->B' })
  it('does not offer interaction or feedback for unsupported renderers', async () => {
    const wrapper = mountViewer()
    wrapper.findComponent({ name: 'Mermaid' }).vm.$emit('highlight-ready', false)
    await wrapper.vm.$nextTick()
    expect(wrapper.find('button').exists()).toBe(false)
    expect(wrapper.find('.highlight-pill').exists()).toBe(false)
  })
  it('forwards capture mode synchronously, hides the pill during capture, and records fullscreen context', async () => {
    forgeGlobal.forgeContext = { extension: { modal: { macroMode: 'fullscreen' } } }
    const wrapper = mountViewer()
    const renderer = wrapper.findComponent({ name: 'Mermaid' })
    const generic = wrapper.findComponent({ name: 'GenericViewer' })
    const capture = vi.spyOn(renderer.vm, 'setCaptureMode')
    generic.vm.$emit('capture-mode-change', true)
    expect(capture).toHaveBeenCalledWith(true)
    renderer.vm.$emit('highlight-ready', true)
    use(renderer, ['node', 'edge', 'node'])
    await wrapper.vm.$nextTick()
    expect(trackAnalyticsEvent).toHaveBeenCalledWith('mermaid_highlight_used', expect.objectContaining({ surface: 'fullscreen', highlight_feedback_variant: 'canvas_pill' }))
    expect(wrapper.find('.highlight-pill').exists()).toBe(false)
    expect(calls('mermaid_highlight_feedback_shown')).toHaveLength(0)
    generic.vm.$emit('capture-mode-change', false)
    await wrapper.vm.$nextTick()
    expect(wrapper.find('.highlight-pill').exists()).toBe(true)
    expect(trackAnalyticsEvent).toHaveBeenCalledWith('mermaid_highlight_feedback_shown', expect.objectContaining({ surface: 'fullscreen', highlight_use_count: 3 }))
  })
  it('starts a new diagram enabled after the previous diagram was disabled', async () => {
    const wrapper = mountViewer()
    const renderer = wrapper.findComponent({ name: 'Mermaid' })
    renderer.vm.$emit('highlight-ready', true)
    await wrapper.vm.$nextTick()
    await wrapper.get('.highlight-toggle').trigger('click')
    expect(renderer.props('relationshipHighlights')).toBe(false)
    store.state.diagram.mermaidCode = 'flowchart LR\nC-->D'
    await wrapper.vm.$nextTick()
    expect(renderer.props('relationshipHighlights')).toBe(true)
    expect(wrapper.emitted('enabled-change')?.at(-1)).toEqual([true])
    renderer.vm.$emit('highlight-ready', true)
    await wrapper.vm.$nextTick()
    expect(wrapper.get('.highlight-toggle').attributes('aria-pressed')).toBe('true')
    await wrapper.get('.highlight-toggle').trigger('click')
    await wrapper.get('.highlight-toggle').trigger('click')
    expect(renderer.props('relationshipHighlights')).toBe(true)
    expect(wrapper.find('.highlight-pill').exists()).toBe(false)
  })
  it('records usage once per diagram but shows the pill only on the third use, and resets the count for a new diagram', async () => {
    const wrapper = mountViewer()
    const renderer = wrapper.findComponent({ name: 'Mermaid' })
    renderer.vm.$emit('highlight-ready', true)
    await wrapper.vm.$nextTick()
    use(renderer, ['node', 'edge'])
    await wrapper.vm.$nextTick()
    expect(wrapper.find('.highlight-pill').exists()).toBe(false)
    expect(wrapper.emitted('usage-change')).toEqual([[true]])
    use(renderer, ['group'])
    await wrapper.vm.$nextTick()
    expect(wrapper.find('.highlight-pill').exists()).toBe(true)
    expect(calls('mermaid_highlight_used')).toHaveLength(1)
    store.state.diagram.id = 'second'
    await wrapper.vm.$nextTick()
    expect(wrapper.emitted('usage-change')?.at(-1)).toEqual([false])
    renderer.vm.$emit('highlight-ready', true)
    use(renderer, ['edge', 'edge'])
    await wrapper.vm.$nextTick()
    expect(wrapper.find('.highlight-pill').exists()).toBe(false)
    use(renderer, ['node'])
    await wrapper.vm.$nextTick()
    expect(wrapper.find('.highlight-pill').exists()).toBe(true)
    expect(calls('mermaid_highlight_used')).toHaveLength(2)
    expect(calls('mermaid_highlight_feedback_shown')).toHaveLength(2)
  })
  it('a dismissed pill stays closed through toggles and for later diagrams', async () => {
    const wrapper = mountViewer()
    const renderer = wrapper.findComponent({ name: 'Mermaid' })
    renderer.vm.$emit('highlight-ready', true)
    use(renderer, ['node', 'edge', 'node'])
    await wrapper.vm.$nextTick()
    await wrapper.get(CLOSE).trigger('click')
    expect(wrapper.find('.highlight-pill').exists()).toBe(false)
    await wrapper.get('.highlight-toggle').trigger('click')
    expect(renderer.props('relationshipHighlights')).toBe(false)
    await wrapper.get('.highlight-toggle').trigger('click')
    expect(wrapper.find('.highlight-pill').exists()).toBe(false)
    store.state.diagram.id = 'second'
    await wrapper.vm.$nextTick()
    renderer.vm.$emit('highlight-ready', true)
    use(renderer, ['edge', 'node', 'group'])
    await wrapper.vm.$nextTick()
    expect(wrapper.find('.highlight-pill').exists()).toBe(false)
    expect(calls('mermaid_highlight_used')).toHaveLength(2)
    expect(calls('mermaid_highlight_feedback_shown')).toHaveLength(1)
  })
})
