-- Migration number: 0024
-- Which viewport rule produced each audience row.
--
-- Until 2026-09-02 the dwell gate observed the attribution footer, a strip of
-- `padding: 8px 12px; font-size: 12px` about 29px tall, at `threshold: 0.5`.
-- A tall diagram could be read in full while that strip stayed below the fold,
-- so the reader was never registered. Measured 2026-08-15..09-02 across four
-- tenants: 4,429 of 41,844 rendered footers reached the dwell (10.6%), and the
-- rate ran 4.2% for sequence against 26.0% for graph, tracking how tall each
-- macro type tends to be.
--
-- The replacement rule observes the diagram itself and asks for
-- `min(200px, half its height)` on screen, so counts written after it lands are
-- not comparable with counts written before. Existing rows are therefore
-- stamped 1 and new rows carry the version that created them; the column is
-- never rewritten on a later view, or the two populations stop being separable.
--
-- Clients already loaded in a browser send no version, which normalizes to 1,
-- so the split stays correct while old builds drain out.

ALTER TABLE DiagramAudience ADD COLUMN gateVersion INTEGER NOT NULL DEFAULT 1;
